linux:
	clang++ main.cpp script/*.cpp -o main

linuxbrew:
	clang++ main.cpp script/*.cpp -o main -I /home/linuxbrew/.linuxbrew/include -L /home/linuxbrew/.linuxbrew/lib -rpath /home/linuxbrew/.linuxbrew/lib